### ISSUE TITLE
i can't build windows version.

### ISSUE THREAD

**Issue by williamfiedler** [unitusdev/unitus#3]
Hi.
I have download unitus-0.14.2 and build ubuntu version successfully.
I think untius is very powerful and useful.
but i can't windows version.
build guide says as following.
           cd depends
           make HOST=x86_64-w64-mingw32
           cd ..
          ./autogen.sh # not required when building from tarball
          CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
          make
but i can't Makefile in depends folder. I have confirmed that there is a makefile in depends folder for bitcoin project.

Please teach me how to build windows version.
I hope your kind answer.
Thank you.

**Comment by nzsquirrell** [comment]
I use a different environment (https://mxe.cc) for the windows builds. Plan to migrate to standard build process soon. Will update the repo when this is working.

**Comment by nzsquirrell** [comment]
Should be working now, changes committed in 9a74e97cac356432f726554459327549cc7e0974

Please test and confirm. Please follow the windows build instructions in /doc, these have also been updated.

**Comment by williamfiedler** [comment]
Great. It's just working.
Thank you, nzsquirrell.
