### ISSUE TITLE
Dependency error on Ubuntu 17.10

### ISSUE THREAD

**Issue by jpfleury** [unitusdev/unitus#5]
Hi,

I'm trying to install the Unitus wallet on the latest Ubuntu version (17.10), but I have this message:

    Error: Dependency is not satisfiable: libprotobuf9v5

On my system, the package installed is libprotobuf10.

**Comment by nzsquirrell** [comment]
Please try the latest release - https://github.com/unitusdev/unitus/releases/tag/0.14.2.1 - this has fewer dependencies due to static libraries being used in the build.

**Comment by jpfleury** [comment]
This version works great. Thanks a lot!
