### ISSUE TITLE
unitus-cli not able to connect to unitusd

### ISSUE THREAD

**Issue by rldleblanc** [unitusdev/unitus#9]
Debian Stretch
Unitus 0.14.2, 0.14.2.1, 0.14.2.2

~/.unitus/unitus.conf
```
rpcuser=unitusrpc
rpcpassword=password
rpcbind=127.0.0.0
server=1
rpcallowip=127.0.0.1
```
```
$ netstat -lnp | grep unitus
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.0:50604         0.0.0.0:*               LISTEN      12582/unitusd
tcp        0      0 0.0.0.0:50603           0.0.0.0:*               LISTEN      12582/unitusd
tcp6       0      0 :::50603                :::*                    LISTEN      12582/unitusd
```
```
$ unitus-cli help
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
```
This machine has DASH and MUE running on it without problems. No firewall.

Any ideas?

Thanks.

**Comment by nzsquirrell** [comment]
change RPC bind to 127.0.0.1 - it's listening on an invalid address, not the loopback interface

**Comment by rldleblanc** [comment]
I feel like such an idiot. I went over the config file many times, but kept missing this. It is working now. Thanks!

**Comment by nzsquirrell** [comment]
haha - we've all been there and done that at least once! :)

**Comment by chalbinov** [comment]
arabic translation done 😄


2018-06-11 6:02 GMT+01:00 nzsquirrell <notifications@github.com>:
